### PR TITLE
Added Ingressroute Support

### LINKED ISSUE #206: Feature Request : Traefik IngressRoute / IngressRouteTCP
Hello, 

First thanks for the app, it's very usefull for us. 

We migrate our cluster to traefik CRDs ingressroute* and we saw that they aren't be supported. 

It would be great to add this feature. We don't dev in go otherwise i would submit a PR

Thanks. 
Chris

### PR DESCRIPTION
**Pull request by Skiepp**
Fixes #206

### CODE REVIEW

**Comment by stakater-user** [comment]
@Skiepp Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/5eb68aa3cba2d194a3631f355a4320b027512516/checks) has Failed!

**Comment by stakater-user** [comment]
@Skiepp Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-272-7448d4ad`

**Review by davidkarlsen — APPROVED** [review]
lgtm, have you tested it? I don't have a cluster with traefik available.
also, can you rebase please?

**Comment by stakater-user** [comment]
@Skiepp Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-272-d884ff50`

**Comment by stakater-user** [comment]
@Skiepp Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-272-b895549c`

**Comment by davidkarlsen** [comment]
@Skiepp have you tested it? you can try with the image referenced in the commens.

**Comment by Skiepp** [comment]
Hi @davidkarlsen, it works just fine with forecastle:SNAPSHOT-PR-272-b895549c :)
Of course, you don't need to install traefik just for test yourself.

First, deploy traefik crd only:
```
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/ingressroute.yaml
```
Secondly, create an IngressRoute resource:
```
cat <<EOF | kubectl apply -n forecastle -f -
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: forecastle
  labels:
    app: forecastle
spec:
  tls: {}
  entryPoints:
  - https
  routes:
  - kind: Rule
    match: Host(`forecastle.domain.example`)
    services:
    - kind: Service
      name: forecastle
      namespace: "forecastle"
      port: 80
EOF
```
Of course, we don't need traefik to reconcile it.

Then, deploy Forecastle with my image:
```
helm upgrade --install -n forecastle \
  --set forecastle.image.tag=SNAPSHOT-PR-272-b895549c \
  --create-namespace \
  forecastle <your-chart-path>
```

Last bu not least, deploy your crd:
```
cat <<EOF | kubectl apply -n forecastle -f -
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: forecastle
spec:
  name: Forecastle
  group: dev
  icon: https://icon-url
  urlFrom:
    ingressRouteRef:
      name: forecastle
EOF
```

Then you can delete all:
```
kubectl delete -f https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/ingressroute.yaml
kubectl delete ns forecastle
```

Cheers

**Review by davidkarlsen — APPROVED** [review]

**Comment by cyxou** [comment]
@Skiepp , thanks fro this implementation.
I've found a bug though (not sure if that relates to `ingressRouteRef` in particular or to `ingressRef ` as well. But the issues is if I use a custom domain name in the IngressRoute Rule, than I get en empty string as url on the Foreastly UI. For example, if you set this url to your IngressRoute:
```sh
 match: Host(`trilium.my.pi`) 
``` 
Than you'll see just `https://trilium.my` on the dashboard:
image

It looks like there is a regex or a parser involved which tries to process the url string in the match Host value and it just strips some unknown domains. Or if I set Host to `trilium.foobar` than I'll get nothing as URL in the Trilium card on the dashboard:
image

**Pull request merged**
