### PR TITLE
updated v1.0.62 with 1.0.64 in all manifests and chart references

### PR DESCRIPTION
**Pull request by sherifkayad**

### CODE REVIEW

**Comment by sherifkayad** [comment]
@rasheedamir @ahmedwaleedmalik Could you please have a look at this one?

**Comment by ahmedwaleedmalik** [comment]
@sherifkayad 

Sorry, but we don't change image/chart/deploy versions like this. Everything is automated and handled through the pipelines. I'll have to close this PR.

**Comment by sherifkayad** [comment]
@ahmedwaleedmalik Then would be great to run those pipelines! 😄

**Comment by ahmedwaleedmalik** [comment]
@sherifkayad I am not actively working on this project. But I'll ask someone to check why the pipelines are not taking care of all of this. Thank you for pointing this out. 

This workflow should have taken care of your use case:
https://github.com/stakater/Forecastle/blob/master/.github/workflows/push.yaml

**Pull request closed without merging**
