### PR TITLE
Add support for customizing imagePullSecrets

### PR DESCRIPTION
**Pull request by tmeltser**
Addition was tested and seems to be working, please review and accept the proposed changes

10x,
Tiran Meltser.

### CODE REVIEW

**Comment by karl-johan-grahn** [comment]
@tmeltser The image is created with the pull request, this is just for your information when you create the pull request, when you do any kind of PR you get the image and can use it for local testing if needed, independent of what kind of change you make

**Comment by tmeltser** [comment]
> @tmeltser The image is created with the pull request, this is just for your information when you create the pull request, when you do any kind of PR you get the image and can use it for local testing if needed, independent of what kind of change you make

Thanks @karl-johan-grahn for the clarification - do I need to do something to promote the PR?

**Comment by karl-johan-grahn** [comment]
@tmeltser We don't have any issue with the change, would just like to understand the requirement before we merge this?

**Comment by tmeltser** [comment]
> @tmeltser We don't have any issue with the change, would just like to understand the requirement before we merge this?

Very simple, the addition allows the forecastle to operate in **air-gapped** environments by allowing setting a suitable image pull secret(s) (as done in many other helm charts)

**Review by LilShah — APPROVED** [review]

**Pull request merged**
