### PR TITLE
Added workflow files and updated makefile

### PR DESCRIPTION
**Pull request by talha0324**

### CODE REVIEW

**Comment by stakater-user** [comment]
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/8e0f739c1269399aadfa51a9df7367721dab4504/checks) has Failed!

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-137-1``

**Comment by stakater-user** [comment]
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/cee365ddd6a3c8894d9eaa467be0e586468344b0/checks) has Failed!

**Comment by stakater-user** [comment]
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/d64e9f282a619f7f7906ad975e4d8fd03c5cb457/checks) has Failed!

**Comment by stakater-user** [comment]
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/ca637518e3f1cf89ffdd22bcb6382d557f02ec32/checks) has Failed!

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-137-3a154e09`

**Comment by rasheedamir** [comment]
@talha0324 will this be merged?

**Pull request merged**
