### PR TITLE
Add ForecastleApp CRD Support

### LINKED ISSUE #73: Feature Request: Support Istio `VirtualService`
Forecastle is wonderful! It's a missing piece in the kubernetes ecosystem.

## what
* Add support for the `VirtualService` CRD

## why
* Forecastle doesn't discover annotations on `VirtualService` CRDs which are used instead of `Ingress` resources to configure routing to backend services

## use-case
* We're moving microservices over to using istio for better tracing and telemetry, but still want to announce services to forecastle.

### PR DESCRIPTION
**Pull request by waseem-h**
- [x] Implement `ForecastleApp` CRD
- [x] Update helm chart
- [x] Add test cases
- [x] Update readme
- [x] Change CRD API Version'

Closes #73

### CODE REVIEW

**Comment by stakater-user** [comment]
@waseem-h Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/Forecastle/job/PR-77/2/) has Failed!

**Comment by stakater-user** [comment]
@waseem-h Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater/job/Forecastle/job/PR-77/1/) has Failed!

**Comment by stakater-user** [comment]
@waseem-h Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/Forecastle/job/PR-77/3/) has Failed!

**Comment by stakater-user** [comment]
@waseem-h Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/Forecastle/job/PR-77/4/) has Failed!

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-5``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-6``

**Comment by osterman** [comment]
Wow! Looks like you put in a lot of work into this. Very grateful for your help!! Will give this a shot.

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-7``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-8``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-9``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-11``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-12``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-13``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-14``

**Comment by stakater-user** [comment]
@waseem-h Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-77-15``

**Pull request merged**
