### PR TITLE
fix: remove ingress.class filters (fixes stakater/Forecastle#106)

### PR DESCRIPTION
**Pull request by ChipWolf**

### CODE REVIEW

**Comment by ChipWolf** [comment]
Tested this change, works as expected.

**Comment by stakater-user** [comment]
@ChipWolf Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-107-2``

**Comment by stakater-user** [comment]
@ChipWolf Image is available for testing. ``docker pull stakater/forecastle:SNAPSHOT-PR-107-4``

**Comment by ahmedwaleedmalik** [comment]
LGTM

**Pull request merged**
