### PR TITLE
Support networking.k8s.io/v1 Ingress

### PR DESCRIPTION
**Pull request by jkroepke**
I take the ingress logic from here:

https://github.com/dexidp/helm-charts/blob/master/charts/dex/templates/ingress.yaml

### CODE REVIEW

**Comment by stakater-user** [comment]
@jkroepke Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-174-23e5821f`

**Comment by stakater-user** [comment]
@jkroepke Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-174-b77f9800`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-174-b77f9800`

**Comment by jkroepke** [comment]
Mention that secrets are not available on external pull request 

https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by davidkarlsen** [comment]
@rasheedamir anything more needed here?

**Review by rasheedamir — APPROVED** [review]

**Review by davidkarlsen — APPROVED** [review]
lgtm

**Comment by davidkarlsen** [comment]
@rasheedamir check https://github.com/stakater/Forecastle/runs/4513715513?check_suite_focus=true - this PR was approved by two, but still it won't pass OK?

**Comment by rasheedamir** [comment]
my mistake! @faizanahmad055 is validating now

**Pull request merged**
