### PR TITLE
Upgrade to golang v1.18

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-4296df29`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-4804a8a2`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-d64db519`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-3a36fda7`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-b05c699d`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-485c7a8a`

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/forecastle:SNAPSHOT-PR-209-2e620523`

**Review by abdulhaseeb2 — APPROVED** [review]
LGTM

**Pull request merged**
