### PR TITLE
Ingress ref crd fix

### PR DESCRIPTION
**Pull request by davidkarlsen**
Obsoletes https://github.com/stakater/Forecastle/pull/176 and fixes both for route and ingress.
@rasheedamir

### CODE REVIEW

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-184-75787566`

**Comment by davidkarlsen** [comment]
@rasheedamir PTAL? Is this project still active?

**Comment by rasheedamir** [comment]
Yes is it @davidkarlsen

**Comment by davidkarlsen** [comment]
Anything more needed for a merge?

**Pull request merged**
