### PR TITLE
WIP: Upgrade to latest k8s apis, upgrade to go 1.17

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. `docker pull stakater/Forecastle:SNAPSHOT-PR-186-4b95295e`

**Review by rasheedamir — APPROVED** [review]

**Comment by rasheedamir** [comment]
@davidkarlsen will you update this PR and do we need to merge it?

**Comment by davidkarlsen** [comment]
> @davidkarlsen will you update this PR and do we need to merge it?

It needs to be fixed. I'll get back when I have time

**Comment by stakater-user** [comment]
@davidkarlsen Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/42b5eecd0945826e58323dca4ad3b4a72fd3ab44/checks) has Failed!

**Comment by stakater-user** [comment]
@davidkarlsen Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/aa43c3df81d3fddd0a3f102030e37616ed9f642b/checks) has Failed!

**Comment by stakater-user** [comment]
@davidkarlsen Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/b64bb51213ce56ae4b74f105abf38df353761532/checks) has Failed!

**Comment by stakater-user** [comment]
@davidkarlsen Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Forecastle/commit/b3132195920b575f76649b9a8c2b4446bb513112/checks) has Failed!

**Pull request closed without merging**
